# Generated by Django 6.0.5 on 2026-06-05 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(db_index=True, max_length=10)),
                ('channel_id', models.PositiveIntegerField(db_index=True)),
                ('channel_label', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('warning', 'Warning (50%)'), ('danger', 'Danger (80%)'), ('exhausted', 'Exhausted (100%)')], db_index=True, max_length=20)),
                ('percent_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_notifications', to='brands.brand')),
            ],
            options={
                'db_table': 'channel_notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_read', 'created_at'], name='channel_not_is_read_9412e5_idx'), models.Index(fields=['brand', 'is_read'], name='channel_not_brand_i_e9c258_idx')],
            },
        ),
        migrations.CreateModel(
            name='DepositLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('qr', 'QR Code'), ('upi', 'UPI Source'), ('bank', 'Bank Account')], db_index=True, max_length=10)),
                ('channel_id', models.PositiveIntegerField(db_index=True)),
                ('client_name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('utr_number', models.CharField(db_index=True, max_length=50)),
                ('deposit_at', models.DateTimeField()),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_logs', to='brands.brand')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deposit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['channel_type', 'channel_id'], name='deposit_log_channel_8e59f3_idx'), models.Index(fields=['brand', 'deposit_at'], name='deposit_log_brand_i_d51b93_idx')],
            },
        ),
    ]
