# Generated by Django 6.0.5 on 2026-06-08 08:20

from django.db import migrations


def drop_index_if_exists(index_name, table_name):
    def _drop(apps, schema_editor):
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(
                "SELECT COUNT(*) FROM information_schema.statistics "
                "WHERE table_schema = DATABASE() AND table_name = %s AND index_name = %s",
                [table_name, index_name],
            )
            if cursor.fetchone()[0]:
                cursor.execute(
                    f"ALTER TABLE `{table_name}` DROP INDEX `{index_name}`"
                )
    return _drop


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0004_depositlog_channel_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='depositlog',
                    name='deposit_log_channel_8e59f3_idx',
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    drop_index_if_exists('deposit_log_channel_8e59f3_idx', 'deposit_logs'),
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveIndex(
                    model_name='depositlog',
                    name='deposit_log_brand_i_d51b93_idx',
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    drop_index_if_exists('deposit_log_brand_i_d51b93_idx', 'deposit_logs'),
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
        ),
        migrations.RenameIndex(
            model_name='depositlog',
            new_name='deposit_log_gateway_6f47e3_idx',
            old_name='deposit_gateway_slip_idx',
        ),
        migrations.RenameIndex(
            model_name='depositlog',
            new_name='deposit_log_status_55fba1_idx',
            old_name='deposit_status_created_idx',
        ),
    ]
