# Generated by Django 6.0.5 on 2026-06-08 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0006_gateway_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('warning', 'Warning'), ('danger', 'Danger'), ('exhausted', 'Exhausted'), ('info', 'Info')], db_index=True, default='info', max_length=20)),
                ('channel_label', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('percent_used', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposit_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='deposits.depositlog')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deposit_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
