# Generated by Django 6.0.5 on 2026-06-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0007_deposit_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositlog',
            name='review_slip',
            field=models.FileField(blank=True, null=True, upload_to='deposit_review_slips/'),
        ),
        migrations.AlterField(
            model_name='depositlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('for_review', 'For Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
