# Generated by Django 6.0.5 on 2026-06-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0008_review_slip_and_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositlog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('for_review', 'For Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20),
        ),
    ]
