# Generated by Django 4.2.23 on 2026-06-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0009_alter_depositlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositlog',
            name='ark_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
