# Generated by Django 6.0.5 on 2026-06-19 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0014_depositmessageread'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='depositmessage',
            new_name='deposit_mes_deposit_c4dcba_idx',
            old_name='deposit_msg_deposit_created_idx',
        ),
    ]
