# Generated by Django 6.0.5 on 2026-06-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0015_rename_deposit_msg_deposit_created_idx_deposit_mes_deposit_c4dcba_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositlog',
            name='channel_type',
            field=models.CharField(blank=True, choices=[('qr', 'QR Code'), ('upi', 'UPI'), ('bank', 'Bank Account'), ('manual', 'Manual')], db_index=True, max_length=10, null=True),
        ),
    ]
