# Generated by Django 6.0.5 on 2026-07-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0016_add_manual_channel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositlog',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='depositlog',
            name='utr_number',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
