# Generated by Django 6.0.5 on 2026-06-03 08:04

import common.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_from', models.DecimalField(decimal_places=2, max_digits=15)),
                ('range_to', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=150)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('branch_name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_sources', to='brands.brand')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bank_accounts',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['brand', 'is_active'], name='bank_accoun_brand_i_48067a_idx')],
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_from', models.DecimalField(decimal_places=2, max_digits=15)),
                ('range_to', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_name', models.CharField(max_length=100)),
                ('qr_image', models.FileField(upload_to=common.utils.generate_qr_upload_path)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_sources', to='brands.brand')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'qr_codes',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['brand', 'is_active'], name='qr_codes_brand_i_445b4e_idx')],
            },
        ),
        migrations.CreateModel(
            name='UPISource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_from', models.DecimalField(decimal_places=2, max_digits=15)),
                ('range_to', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upi_id', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_sources', to='brands.brand')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'upi_sources',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['brand', 'is_active'], name='upi_sources_brand_i_7aaf19_idx')],
            },
        ),
    ]
