# Generated by Django 6.0.5 on 2026-06-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_bankaccount_daily_limit_qrcode_daily_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='qr_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
