# Generated by Django 6.0.5 on 2026-06-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_add_gateway_to_payment_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='upisource',
            name='gateway',
        ),
    ]
