# Generated by Django 6.0.5 on 2026-06-20 08:07
"""
Step 1: Remove old indexes and add M2M brands fields (keeping old FK columns alive).
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('payments', '0005_remove_bankaccount_gateway_remove_qrcode_gateway_and_more'),
    ]

    operations = [
        # ── Remove composite indexes that reference the old FK ────────────
        migrations.RemoveIndex(
            model_name='bankaccount',
            name='bank_accoun_brand_i_48067a_idx',
        ),
        migrations.RemoveIndex(
            model_name='qrcode',
            name='qr_codes_brand_i_445b4e_idx',
        ),
        migrations.RemoveIndex(
            model_name='upisource',
            name='upi_sources_brand_i_7aaf19_idx',
        ),
        # ── Add new M2M brands fields ────────────────────────────────────
        migrations.AddField(
            model_name='bankaccount',
            name='brands',
            field=models.ManyToManyField(
                blank=True,
                db_table='bank_account_brands',
                related_name='bank_account_sources',
                to='brands.brand',
            ),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='brands',
            field=models.ManyToManyField(
                blank=True,
                db_table='qr_code_brands',
                related_name='qr_code_sources',
                to='brands.brand',
            ),
        ),
        migrations.AddField(
            model_name='upisource',
            name='brands',
            field=models.ManyToManyField(
                blank=True,
                db_table='upi_source_brands',
                related_name='upi_sources',
                to='brands.brand',
            ),
        ),
    ]
