# Generated by Django 6.0.5 on 2026-06-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_remove_brand_fk_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='branch_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
