# Generated by Django 6.0.5 on 2026-06-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_default_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('users', 'Users'), ('brands', 'Brands'), ('qr_codes', 'QR Codes'), ('upi_sources', 'UPI Sources'), ('bank_accounts', 'Bank Accounts'), ('audit_logs', 'Audit Logs'), ('deposits', 'Deposits')], max_length=50),
        ),
    ]
