# Generated by Django 6.0.5 on 2026-06-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_alter_rolepermission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('roles', 'Roles'), ('users', 'Users'), ('brands', 'Brands'), ('gateways', 'Gateways'), ('qr_codes', 'QR Codes'), ('upi_sources', 'UPI Sources'), ('bank_accounts', 'Bank Accounts'), ('deposits', 'Deposits'), ('withdrawals', 'Withdrawals'), ('audit_logs', 'Audit Logs')], max_length=50),
        ),
    ]
