# Generated by Django 6.0.5 on 2026-06-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_alter_rolepermission_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('roles', 'Roles'), ('users', 'Users'), ('brands', 'Brands'), ('gateways', 'Gateways'), ('qr_codes', 'QR Codes'), ('upi_sources', 'UPI Sources'), ('bank_accounts', 'Bank Accounts'), ('deposits', 'Deposits'), ('deposit_history', 'Deposit History'), ('withdrawals', 'Withdrawals'), ('withdrawal_history', 'Withdrawal History'), ('audit_logs', 'Audit Logs')], max_length=50),
        ),
    ]
