# Generated by Django 6.0.5 on 2026-06-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0006_seed_history_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='scope',
            field=models.CharField(choices=[('all', 'All — can see all records'), ('brand', 'Brand — can see records from assigned brands'), ('own', 'Own — can only see own records')], default='own', help_text='Determines what data users with this role can access.', max_length=10),
        ),
    ]
