# Generated by Django 6.0.5 on 2026-06-12 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0008_set_existing_role_scopes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='scope',
        ),
    ]
