# Generated by Django 6.0.5 on 2026-06-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0009_remove_scope_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('roles', 'Roles'), ('users', 'Users'), ('brands', 'Brands'), ('audit_logs', 'Audit Logs'), ('master', 'Master'), ('payment_methods', 'Payment Methods'), ('transactions', 'Transactions'), ('gateways', 'Gateways'), ('qr_codes', 'QR Codes'), ('upi_sources', 'UPI Sources'), ('bank_accounts', 'Bank Accounts'), ('deposits', 'Deposits'), ('deposit_history', 'Deposit History'), ('withdrawals', 'Withdrawals'), ('withdrawal_history', 'Withdrawal History')], max_length=50),
        ),
    ]
