# Generated by Django 6.0.5 on 2026-06-15 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0012_rolepermission_can_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='can_chat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_close_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_confirm_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_email_bank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_not_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='can_upload_slip',
            field=models.BooleanField(default=False),
        ),
    ]
