# Generated by Django 6.0.5 on 2026-06-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0013_add_action_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='can_view_details',
            field=models.BooleanField(default=False),
        ),
    ]
