# Generated by Django 6.0.5 on 2026-06-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0002_withdrawal_simplify'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='attachment',
        ),
    ]
