# Generated by Django 6.0.5 on 2026-06-06 10:06

import django.db.models.deletion
import withdrawals.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0003_remove_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='bank_followup_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='followup_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='slip',
            field=models.FileField(blank=True, null=True, upload_to=withdrawals.models.withdrawal_slip_upload_path),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='slip_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='slip_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='slip_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_slips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('slip_uploaded', 'Slip Uploaded'), ('bank_followup_required', 'Bank Follow-Up Required'), ('email_sent_to_bank', 'Email Sent to Bank'), ('closed', 'Closed'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='WithdrawalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('slip_uploaded', 'Slip Uploaded'), ('followup_required', 'Follow-Up Required'), ('email_sent_to_bank', 'Email Sent to Bank'), ('closed', 'Ticket Closed')], max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_notifications', to=settings.AUTH_USER_MODEL)),
                ('withdrawal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='withdrawals.withdrawal')),
            ],
            options={
                'db_table': 'withdrawal_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
