# Generated by Django 6.0.5 on 2026-06-06 11:37

import django.db.models.deletion
import withdrawals.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0004_withdrawal_bank_followup_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalnotification',
            name='notif_type',
            field=models.CharField(choices=[('slip_uploaded', 'Slip Uploaded'), ('followup_required', 'Follow-Up Required'), ('email_sent_to_bank', 'Email Sent to Bank'), ('closed', 'Ticket Closed'), ('new_message', 'New Message'), ('manual_closed', 'Manually Closed')], max_length=30),
        ),
        migrations.CreateModel(
            name='WithdrawalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=withdrawals.models.withdrawal_message_upload_path)),
                ('attachment_name', models.CharField(blank=True, max_length=255)),
                ('is_protected', models.BooleanField(default=False)),
                ('password_hint', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_messages', to=settings.AUTH_USER_MODEL)),
                ('withdrawal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='withdrawals.withdrawal')),
            ],
            options={
                'db_table': 'withdrawal_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['withdrawal', 'created_at'], name='withdrawal__withdra_9eabce_idx')],
            },
        ),
    ]
