# Generated by Django 6.0.5 on 2026-06-18 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0005_alter_withdrawalnotification_notif_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalMessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_message_reads', to=settings.AUTH_USER_MODEL)),
                ('withdrawal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reads', to='withdrawals.withdrawal')),
            ],
            options={
                'db_table': 'withdrawal_message_reads',
                'indexes': [models.Index(fields=['withdrawal', 'user'], name='withdrawal__withdra_e13b6b_idx')],
                'unique_together': {('withdrawal', 'user')},
            },
        ),
    ]
